

services:
  # 1. VERÄ°TABANI (POSTGRES)
  db:
    image: postgres:16-alpine
    container_name: cari_db  # Ä°sim dÃ¼zeltildi
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      

  # 2. PGADMIN (DB YÃ¶netim Paneli)
  pgadmin:
    image: dpage/pgadmin4
    container_name: cari_pgadmin # Ä°sim dÃ¼zeltildi
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@sistem.com # Jenerik mail
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

  # 3. BACKEND (API)
  api:
    build: ./backend
    container_name: cari_api # Ä°sim dÃ¼zeltildi
    command: npm run dev
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
      PORT: 3000
    volumes:
      - ./backend:/app
      - /app/node_modules
      # ðŸ‘‡ Ä°ÅžTE BU SATIR SÄ°HÄ°RLÄ°! Senin C diskini Backend'e baÄŸlÄ±yoruz
      # - C:/Users/mbice/Desktop/Cari_ERP_Sistem/demo/assets/img:/app/uploads
    depends_on:
      - db

volumes:
  postgres_data: